//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.MillCertificateSheetService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/COM.Dtos")]
    [System.SerializableAttribute()]
    public partial class RegisterRequestDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocMngNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssuedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MillSheetNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocMngNo {
            get {
                return this.DocMngNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocMngNoField, value) != true)) {
                    this.DocMngNoField = value;
                    this.RaisePropertyChanged("DocMngNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssuedDate {
            get {
                return this.IssuedDateField;
            }
            set {
                if ((this.IssuedDateField.Equals(value) != true)) {
                    this.IssuedDateField = value;
                    this.RaisePropertyChanged("IssuedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MillSheetNo {
            get {
                return this.MillSheetNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MillSheetNoField, value) != true)) {
                    this.MillSheetNoField = value;
                    this.RaisePropertyChanged("MillSheetNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectNo {
            get {
                return this.ProjectNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNoField, value) != true)) {
                    this.ProjectNoField = value;
                    this.RaisePropertyChanged("ProjectNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MillSheetResponseDTO", Namespace="http://schemas.datacontract.org/2004/07/COM.Dtos")]
    [System.SerializableAttribute()]
    public partial class MillSheetResponseDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocMngNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssuedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MillSheetNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ModifiedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateAt {
            get {
                return this.CreateAtField;
            }
            set {
                if ((this.CreateAtField.Equals(value) != true)) {
                    this.CreateAtField = value;
                    this.RaisePropertyChanged("CreateAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocMngNo {
            get {
                return this.DocMngNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocMngNoField, value) != true)) {
                    this.DocMngNoField = value;
                    this.RaisePropertyChanged("DocMngNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssuedDate {
            get {
                return this.IssuedDateField;
            }
            set {
                if ((this.IssuedDateField.Equals(value) != true)) {
                    this.IssuedDateField = value;
                    this.RaisePropertyChanged("IssuedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MillSheetNo {
            get {
                return this.MillSheetNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MillSheetNoField, value) != true)) {
                    this.MillSheetNoField = value;
                    this.RaisePropertyChanged("MillSheetNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ModifiedAt {
            get {
                return this.ModifiedAtField;
            }
            set {
                if ((this.ModifiedAtField.Equals(value) != true)) {
                    this.ModifiedAtField = value;
                    this.RaisePropertyChanged("ModifiedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectNo {
            get {
                return this.ProjectNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNoField, value) != true)) {
                    this.ProjectNoField = value;
                    this.RaisePropertyChanged("ProjectNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModifyRequestDTO", Namespace="http://schemas.datacontract.org/2004/07/COM.Dtos")]
    [System.SerializableAttribute()]
    public partial class ModifyRequestDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocMngNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssuedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MillSheetNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocMngNo {
            get {
                return this.DocMngNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocMngNoField, value) != true)) {
                    this.DocMngNoField = value;
                    this.RaisePropertyChanged("DocMngNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssuedDate {
            get {
                return this.IssuedDateField;
            }
            set {
                if ((this.IssuedDateField.Equals(value) != true)) {
                    this.IssuedDateField = value;
                    this.RaisePropertyChanged("IssuedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MillSheetNo {
            get {
                return this.MillSheetNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MillSheetNoField, value) != true)) {
                    this.MillSheetNoField = value;
                    this.RaisePropertyChanged("MillSheetNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectNo {
            get {
                return this.ProjectNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNoField, value) != true)) {
                    this.ProjectNoField = value;
                    this.RaisePropertyChanged("ProjectNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MillCertificateSheetService.IMillCertificateSheetService")]
    public interface IMillCertificateSheetService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/Add", ReplyAction="http://tempuri.org/IMillCertificateSheetService/AddResponse")]
        UI.MillCertificateSheetService.MillSheetResponseDTO Add(UI.MillCertificateSheetService.RegisterRequestDTO registerRequestDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/Add", ReplyAction="http://tempuri.org/IMillCertificateSheetService/AddResponse")]
        System.Threading.Tasks.Task<UI.MillCertificateSheetService.MillSheetResponseDTO> AddAsync(UI.MillCertificateSheetService.RegisterRequestDTO registerRequestDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/AddRange", ReplyAction="http://tempuri.org/IMillCertificateSheetService/AddRangeResponse")]
        UI.MillCertificateSheetService.MillSheetResponseDTO[] AddRange(UI.MillCertificateSheetService.RegisterRequestDTO[] registerRequestDtos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/AddRange", ReplyAction="http://tempuri.org/IMillCertificateSheetService/AddRangeResponse")]
        System.Threading.Tasks.Task<UI.MillCertificateSheetService.MillSheetResponseDTO[]> AddRangeAsync(UI.MillCertificateSheetService.RegisterRequestDTO[] registerRequestDtos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/Modify", ReplyAction="http://tempuri.org/IMillCertificateSheetService/ModifyResponse")]
        void Modify(UI.MillCertificateSheetService.ModifyRequestDTO modifyRequestDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/Modify", ReplyAction="http://tempuri.org/IMillCertificateSheetService/ModifyResponse")]
        System.Threading.Tasks.Task ModifyAsync(UI.MillCertificateSheetService.ModifyRequestDTO modifyRequestDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/DeleteById", ReplyAction="http://tempuri.org/IMillCertificateSheetService/DeleteByIdResponse")]
        void DeleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/DeleteById", ReplyAction="http://tempuri.org/IMillCertificateSheetService/DeleteByIdResponse")]
        System.Threading.Tasks.Task DeleteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/GetAll", ReplyAction="http://tempuri.org/IMillCertificateSheetService/GetAllResponse")]
        UI.MillCertificateSheetService.MillSheetResponseDTO[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/GetAll", ReplyAction="http://tempuri.org/IMillCertificateSheetService/GetAllResponse")]
        System.Threading.Tasks.Task<UI.MillCertificateSheetService.MillSheetResponseDTO[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/GetByCreatedAt", ReplyAction="http://tempuri.org/IMillCertificateSheetService/GetByCreatedAtResponse")]
        UI.MillCertificateSheetService.MillSheetResponseDTO[] GetByCreatedAt(System.DateTime createdAt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/GetByCreatedAt", ReplyAction="http://tempuri.org/IMillCertificateSheetService/GetByCreatedAtResponse")]
        System.Threading.Tasks.Task<UI.MillCertificateSheetService.MillSheetResponseDTO[]> GetByCreatedAtAsync(System.DateTime createdAt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/GetByCategoryAndKeyword", ReplyAction="http://tempuri.org/IMillCertificateSheetService/GetByCategoryAndKeywordResponse")]
        UI.MillCertificateSheetService.MillSheetResponseDTO[] GetByCategoryAndKeyword(string category, string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMillCertificateSheetService/GetByCategoryAndKeyword", ReplyAction="http://tempuri.org/IMillCertificateSheetService/GetByCategoryAndKeywordResponse")]
        System.Threading.Tasks.Task<UI.MillCertificateSheetService.MillSheetResponseDTO[]> GetByCategoryAndKeywordAsync(string category, string keyword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMillCertificateSheetServiceChannel : UI.MillCertificateSheetService.IMillCertificateSheetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MillCertificateSheetServiceClient : System.ServiceModel.ClientBase<UI.MillCertificateSheetService.IMillCertificateSheetService>, UI.MillCertificateSheetService.IMillCertificateSheetService {
        
        public MillCertificateSheetServiceClient() {
        }
        
        public MillCertificateSheetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MillCertificateSheetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MillCertificateSheetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MillCertificateSheetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UI.MillCertificateSheetService.MillSheetResponseDTO Add(UI.MillCertificateSheetService.RegisterRequestDTO registerRequestDto) {
            return base.Channel.Add(registerRequestDto);
        }
        
        public System.Threading.Tasks.Task<UI.MillCertificateSheetService.MillSheetResponseDTO> AddAsync(UI.MillCertificateSheetService.RegisterRequestDTO registerRequestDto) {
            return base.Channel.AddAsync(registerRequestDto);
        }
        
        public UI.MillCertificateSheetService.MillSheetResponseDTO[] AddRange(UI.MillCertificateSheetService.RegisterRequestDTO[] registerRequestDtos) {
            return base.Channel.AddRange(registerRequestDtos);
        }
        
        public System.Threading.Tasks.Task<UI.MillCertificateSheetService.MillSheetResponseDTO[]> AddRangeAsync(UI.MillCertificateSheetService.RegisterRequestDTO[] registerRequestDtos) {
            return base.Channel.AddRangeAsync(registerRequestDtos);
        }
        
        public void Modify(UI.MillCertificateSheetService.ModifyRequestDTO modifyRequestDto) {
            base.Channel.Modify(modifyRequestDto);
        }
        
        public System.Threading.Tasks.Task ModifyAsync(UI.MillCertificateSheetService.ModifyRequestDTO modifyRequestDto) {
            return base.Channel.ModifyAsync(modifyRequestDto);
        }
        
        public void DeleteById(int id) {
            base.Channel.DeleteById(id);
        }
        
        public System.Threading.Tasks.Task DeleteByIdAsync(int id) {
            return base.Channel.DeleteByIdAsync(id);
        }
        
        public UI.MillCertificateSheetService.MillSheetResponseDTO[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<UI.MillCertificateSheetService.MillSheetResponseDTO[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public UI.MillCertificateSheetService.MillSheetResponseDTO[] GetByCreatedAt(System.DateTime createdAt) {
            return base.Channel.GetByCreatedAt(createdAt);
        }
        
        public System.Threading.Tasks.Task<UI.MillCertificateSheetService.MillSheetResponseDTO[]> GetByCreatedAtAsync(System.DateTime createdAt) {
            return base.Channel.GetByCreatedAtAsync(createdAt);
        }
        
        public UI.MillCertificateSheetService.MillSheetResponseDTO[] GetByCategoryAndKeyword(string category, string keyword) {
            return base.Channel.GetByCategoryAndKeyword(category, keyword);
        }
        
        public System.Threading.Tasks.Task<UI.MillCertificateSheetService.MillSheetResponseDTO[]> GetByCategoryAndKeywordAsync(string category, string keyword) {
            return base.Channel.GetByCategoryAndKeywordAsync(category, keyword);
        }
    }
}
